"""Update

Revision ID: b83b1a0a6c63
Revises: d1ec99418059
Create Date: 2024-08-23 08:30:01.653274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83b1a0a6c63'
down_revision = 'd1ec99418059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birth_certificates', schema=None) as batch_op:
        batch_op.alter_column('gks_ngayDangKy',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birth_certificates', schema=None) as batch_op:
        batch_op.alter_column('gks_ngayDangKy',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
