"""Initial migration

Revision ID: d1ec99418059
Revises: 396853b9f8e0
Create Date: 2024-08-23 08:13:59.841391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ec99418059'
down_revision = '396853b9f8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birth_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cha_noiThuongTruTamTru', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('me_noiThuongTruTamTru', sa.String(length=100), nullable=True))
        batch_op.alter_column('con_ngaySinh',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('cha_namSinh',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('me_namSinh',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('me_noiThuongTru')
        batch_op.drop_column('cha_noiThuongTru')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birth_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cha_noiThuongTru', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('me_noiThuongTru', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('me_namSinh',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('cha_namSinh',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('con_ngaySinh',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('me_noiThuongTruTamTru')
        batch_op.drop_column('cha_noiThuongTruTamTru')

    # ### end Alembic commands ###
